import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Welcome to Futurama 입니다</h1>
			</main>

			<footer>
				<p>
					Powered by <span>BORI</span>
				</p>
			</footer>
		</div>
	);
};

export default Home;
