import styled from '@emotion/styled';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Welcome to Futurama</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<HomeContainer></HomeContainer>
		</div>
	);
};

export default Home;

const HomeContainer = styled.section`
	width: 100vw;
	min-height: calc(100vh - 96px);
	box-sizing: border-box;
	background-color: rgba(0, 0, 0, 0.5);
`;
